### ISSUE TITLE
rmcat - where is the output file?

### ISSUE THREAD

**Issue by qwert2003** [kg4zow/rm2-scripts#6]
When I try
```
rmcat -o testrmcat.rmdoc out-myfillrect.rmdoc out-myfillrect2.rmdoc 
READ    out-myfillrect.rmdoc
READ    out-myfillrect2.rmdoc
CREATE  testrmcat.rmdoc
```
I do not find the resulting file testrmcat.rmdoc. There is no error message.

When using the option -k I can find the notebook file in the temporary directory.
When using the option -x I see the last command `mv '/tmp/vCXFQc8WQc/output.rmdoc' 'testrmcat.rmdoc'`

If I run that last command (after having run rmcat with the option -k) the file gets moved to the working directory.
So the issues seems to be related to this command (does it move to the wrong place?).

Context: Linux computer
```
perl --version

This is perl 5, version 26, subversion 1 (v5.26.1) built for x86_64-linux-thread-multi
```

**Comment by kg4zow** [comment]
I'm going to *guess* that on your computer, `/tmp` is on a different filesytem than whatever the current directory is where you're running the script.

If so, the problem is that the script *prints* an `mv` command, but it actually *uses* Perl's built in `rename()` function to move the file, and it doesn't check the output from that function to make sure it worked.

I just tried it again on my computer (macOS, but the same things apply on Linux). When I've used it in the past, I was always working with files that were on the machine's internal disk, and for macOS the "temp directory" is on the `/` filesystem (with a weird convoluted name, but still *on* that filesytem). This time I happened to be using files stored in a [Keybase](https://keybase.io/) directory, which is mounted as a different filesystem. I got the same results you did - it *looked like* it worked, but no output file. Turns out when I added a check on the `rename()` call, I got this ...

```
(jms1@M2Air15) 48 /keybase/public/jms1/rmcat-issue-6 $ rmcat -o combined.rmdoc Dates-2024.rmdoc Dates-2025.rmdoc
READ    Dates-2024.rmdoc
  FILE    d9ed2cf2-d50f-40c7-924f-72e02bd0b445.highlights
  FILE    d9ed2cf2-d50f-40c7-924f-72e02bd0b445.local
  FILE    d9ed2cf2-d50f-40c7-924f-72e02bd0b445.textconversion
  FILE    d9ed2cf2-d50f-40c7-924f-72e02bd0b445.thumbnails
READ    Dates-2025.rmdoc
  FILE    4f624f8c-7560-45d1-bdac-c2759c7399e6.highlights
  FILE    4f624f8c-7560-45d1-bdac-c2759c7399e6.local
  FILE    4f624f8c-7560-45d1-bdac-c2759c7399e6.textconversion
  FILE    4f624f8c-7560-45d1-bdac-c2759c7399e6.thumbnails
CREATE  combined.rmdoc
ERROR: rename(): Cross-device link
```

So.

Instead of using `rename()`, I'm updating the script to actually run the same `mv` command that it prints, since the `mv` command will "copy then delete" files that it moves from one filesystem to another.

```
(jms1@M2Air15) 59 /keybase/public/jms1/rmcat-issue-6 $ rmcat -x -o combined.rmdoc Dates-2024.rmdoc Dates-2025.rmdoc
READ    Dates-2024.rmdoc
+ unzip -q -d '/var/folders/8_/3tf1_3_n5tl9q88w7rbh0bnm0000gn/T/BF3EbQfuBr/in' 'Dates-2024.rmdoc'
  FILE    d9ed2cf2-d50f-40c7-924f-72e02bd0b445.highlights
  FILE    d9ed2cf2-d50f-40c7-924f-72e02bd0b445.local
  FILE    d9ed2cf2-d50f-40c7-924f-72e02bd0b445.textconversion
  FILE    d9ed2cf2-d50f-40c7-924f-72e02bd0b445.thumbnails
READ    Dates-2025.rmdoc
+ unzip -q -d '/var/folders/8_/3tf1_3_n5tl9q88w7rbh0bnm0000gn/T/BF3EbQfuBr/in' 'Dates-2025.rmdoc'
  FILE    4f624f8c-7560-45d1-bdac-c2759c7399e6.highlights
  FILE    4f624f8c-7560-45d1-bdac-c2759c7399e6.local
  FILE    4f624f8c-7560-45d1-bdac-c2759c7399e6.textconversion
  FILE    4f624f8c-7560-45d1-bdac-c2759c7399e6.thumbnails
CREATE  combined.rmdoc
+ ( cd '/var/folders/8_/3tf1_3_n5tl9q88w7rbh0bnm0000gn/T/BF3EbQfuBr' ; zip -r -q output.rmdoc * )
+ mv '/var/folders/8_/3tf1_3_n5tl9q88w7rbh0bnm0000gn/T/BF3EbQfuBr/output.rmdoc' 'combined.rmdoc'
```

I'll be pushing an update to the script in a bit. Please try that and let me know how it goes.

Also, if you want to try using the actual files I tested this with, you can copy them from `/keybase/public/jms1/rmcat-issue-6/` or, if you don't have Keybase, you can download them from [here](https://jms1.pub/rmcat-issue-6/) using a browser.

**Comment by qwert2003** [comment]
It works, thanks!

**Comment by kg4zow** [comment]
Glad this was such an easy fix. Thanks for letting me know about it.
